### ISSUE TITLE
直播没有声音

### ISSUE THREAD

**Issue by AmpletecGo** [zhw2590582/flv-player#12]
### Expected behaviour
直播需要声音
### Actual behaviour
没有声音
### Environment

-   Browser:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
-   Version:1.1.1
-   Operating System:(Windows NT 10.0
-   Version:(Windows NT 10.0

**Comment by zhw2590582** [comment]
这个直播的音频还没写完.

**Comment by Slodezzm** [comment]
大佬您赶紧写完啊
