### ISSUE TITLE
总时间显示错误

### ISSUE THREAD

**Issue by jiajun00** [zhw2590582/flv-player#15]
<img width="1682" alt="截屏2019-10-2312 51 18" src="https://user-images.githubusercontent.com/14782540/67359278-6ed69680-f595-11e9-85ed-86080b3c0f32.png">

### Environment

-   Browser:chrome
-   Version:77.0.3865.120
-   Operating System:mac
-   Version:

**Comment by zhw2590582** [comment]
应该是flv文件里没有带有`duration`属性，你可以在实例化的时候直接传入一个`duration`，单位为秒，比如：

```js
var flv = new FlvPlayer({
    duration: 100
})
```
