### ISSUE TITLE
ws flv 流,用flv.js可以正常播放,如果用flvPlayer canvas播放器会空白,但是流正常

### ISSUE THREAD

**Issue by 1032740078** [zhw2590582/flv-player#16]
### Expected behaviour
正常播放ws flv视频
### Actual behaviour
播放器空白,无法正常播放,流正常
### Environment

-   Browser:谷歌浏览器
-   Version:
-   Operating System:windows 10
-   Version:

### Console errors (if any)
![image](https://user-images.githubusercontent.com/32318856/67635333-4f729d00-f8f8-11e9-8f12-3c56290a629b.png)

**Comment by zhw2590582** [comment]
profile是high，可以换个解码器试试

**Comment by 1032740078** [comment]
> 个人资料是高，可以换个解码器试试

换成flvplayer-decoder-multiple.js后,canvas只显示第一帧的画面,然后就不播放了,画面不动了
![image](https://user-images.githubusercontent.com/32318856/67636162-3c63cb00-f900-11e9-9e30-2d29c015edeb.png)

**Comment by 1032740078** [comment]
这是我写的源码

![image](https://user-images.githubusercontent.com/32318856/67636190-abd9ba80-f900-11e9-85b0-ba6437bba0d5.png)

**Comment by zhw2590582** [comment]
试下把`hasAudio`关闭，`flvplayer-decoder-multiple.js`解码效果不是很好，正在找新的解码器，或者可以的话，在服务器端把`flv`的`profile`转为`baseline`，再用`flvplayer-decoder-baseline.js`

**Comment by 1032740078** [comment]
> 试下把`hasAudio`关闭，`flvplayer-decoder-multiple.js`解码效果不是很好，正在找新的解码器，或者可以的话，在服务器端把`flv`的`profile`转为`baseline`，再用`flvplayer-decoder-baseline.js`

好的，谢谢你
