### ISSUE TITLE
flvplayer使用flvplayer-decoder-multiple解码右上角展现的当前时间

### ISSUE THREAD

**Issue by kentpan** [zhw2590582/flv-player#17]
![image](https://user-images.githubusercontent.com/1459668/67648072-8df76e80-f96f-11e9-813a-6adf52844c66.png)
找了一圈没发现是yuv解码时附加了还是在canvas展现时才加的。。。 >_< !!!
这个当前时间是否可以设置/隐藏？或者可以作为配置项进行图片/文字水印设置吗？

**Comment by zhw2590582** [comment]
这是码流自带的水印吧，我这边肯定不会加这个东西的
