### ISSUE TITLE
iOS下播放HTTP-FLV点击全屏按钮无效

### ISSUE THREAD

**Issue by kentpan** [zhw2590582/flv-player#18]
### Environment

-   Browser:
-   Version:
-   Operating System:
-   Version:

**Comment by zhw2590582** [comment]
是无效的，因为这不是视频标签。

**Comment by kentpan** [comment]
但可以通过CSS3模拟窗口全屏效果

**Comment by zhw2590582** [comment]
已经是css模拟全屏了，难道有兼容问题？可以的话截个图看看

**Comment by kentpan** [comment]
![image](https://user-images.githubusercontent.com/1459668/71649888-55985600-2d4d-11ea-83aa-27e0e7450342.png)
发现问题了, 是因为父元素上有transform属性导致, 请问下有fullscreen事件吗? 建议各事件可以跟videojs对齐
