### ISSUE TITLE
vue 无法获取到 decoder

### ISSUE THREAD

**Issue by Hunlongyu** [zhw2590582/flv-player#19]
### Expected behaviour
vue 中如何引入 flvplayer-decoder-baseline.js 文件啊?
### Environment

-   Browser: chrome
-   Version: 79.0.3945.88
-   Operating System: win10
-   Version: 1909

### Console errors (if any)
![Snipaste_2019-12-20_15-28-54.png](https://i.loli.net/2019/12/20/ZSrLxwCuj1GgVTM.png)
![carbon.png](https://i.loli.net/2019/12/20/LQieW5jwyasgB2z.png)
![carbon](https://user-images.githubusercontent.com/15273630/71237915-c139f680-233d-11ea-924e-0e1fea9cb0a6.png)
### Link to where the bug is happening
![carbon (1)](https://user-images.githubusercontent.com/15273630/71237936-d0b93f80-233d-11ea-9a15-ec08330c2c6e.png)
![carbon (1).png](https://i.loli.net/2019/12/20/GPXTYJuDAnLgcjS.png)

**Comment by zhw2590582** [comment]
`flvplayer-decoder-baseline.js`是一个单独文件，Vue是不会把他打包的，你可以相对引用或者绝对引用, 直接`decoder`填路径就好，注意`decoder`是从根目录开始查找的，不是你写的那个JS文件开始查找。

```js
new FlvPlayer({
   decoder: 'flvplayer-decoder-baseline.js',
})
```

**Comment by Hunlongyu** [comment]
![carbon (2)](https://user-images.githubusercontent.com/15273630/71242673-69a18800-2349-11ea-882d-c09c9288c68e.png)
![Snipaste](https://user-images.githubusercontent.com/15273630/71242686-70c89600-2349-11ea-9037-7cc1b1b188bd.png)

我设置  hasAudio: false
但还是报音频错误

**Comment by zhw2590582** [comment]
最后有画面输出么，我这个库，音频只支持aac

**Comment by Hunlongyu** [comment]
> 最后有画面输出么，我这个库，音频只支持aac

没有输出视频画面
bilibili 的 flv.js  的 hasAudio: true 时, 也报错. 
但是 flv.js 设置为 hasAudio: false 时,不会报错.

FlvPlayer 的 hasAudio: false 时,报错

**Comment by zhw2590582** [comment]
有道理，我后面再改下这个逻辑

**Comment by Hunlongyu** [comment]
话说这个 decoder 的引入方式,可以改变一下吗?
类似这种: 
![carbon (4)](https://user-images.githubusercontent.com/15273630/71246896-98702c00-2352-11ea-835b-bc2a92914441.png)

**Comment by zhw2590582** [comment]
不能，因为`decoder `不是一个普通模块，而是一个`worker`

**Comment by AhJane** [comment]
也遇到在vue里引入不了decoder的问题，各种路径都试过了，不填使用默认配置也不行。请问作者大大没有其他的引入方式了吗？😂😂

**Comment by zhw2590582** [comment]
@AhJane 假如你找不到相对路径，那可以直接写绝对路径

**Comment by AhJane** [comment]
> @AhJane 假如你找不到相对路径，那可以直接写绝对路径

相对路径、绝对路径都找不到呀😂

**Comment by zhw2590582** [comment]
@AhJane 截图看看报什么错

**Comment by AhJane** [comment]
@zhw2590582 跟开这个issue的兄弟一样呢
![image](https://user-images.githubusercontent.com/11899930/71883176-d05bd980-3170-11ea-9985-5d48ee6e3fa8.png)

**Comment by AhJane** [comment]
@zhw2590582 各种路径组合我都试过了，仍然报这个错呢😭

**Comment by zhw2590582** [comment]
@AhJane 假如你是用vue-cli生成的项目，你可以把 `flvplayer-decoder-baseline.js` 放到你的`public`目录，然后直接这样，因为webpack改写了静态资源的访问路径，所以导致很容易找不到相对路径。

```js
var flv = new FlvPlayer({
  container: ".flvplayer-app",
  url: "https://flvplayer.js.org/assets/video/weathering-with-you.flv",
  decoder: "flvplayer-decoder-baseline.js",
});
```

**Comment by AhJane** [comment]
@zhw2590582 按照你说的这种方法可以找到了，谢谢
