### ISSUE TITLE
Source code for decoder.worker

### ISSUE THREAD

**Issue by talltyler** [zhw2590582/flv-player#21]
Is the source for the decoder.worker files available?

**Comment by zhw2590582** [comment]
Of course!

**Comment by talltyler** [comment]
Please post a link when you do. I would love to see how this works.

**Comment by zhw2590582** [comment]
Sorry, I don't understand what you need. Do you need the source code of decoder.worker?
It comes from [tinyh264](https://github.com/udevbe/tinyh264)

**Comment by talltyler** [comment]
Thank you for this information about this being based on tinyh264, that is good to know I didn't see information about this in any of the documentation. But how are you compiling this project? Can you include the build scrips or commands that you are using?

**Comment by zhw2590582** [comment]
I just compiled the `wasm` file to `base64` for convenience. Actually you don't need to do this.
[h264bsd](https://github.com/oneam/h264bsd/tree/master/wasm) and [tinyh264](https://github.com/udevbe/tinyh264) both provide examples for reference.

```js
const wasm = fs.readFileSync(__dirname + '/tinyh264.wasm', 'base64');
const dataUrl = 'data:application/octet-stream;base64,' + wasm;
```

**Comment by talltyler** [comment]
Thank you all of this has helped, I think we can close this issue.
