### ISSUE TITLE
只有aac音频文件好像不能播放

### ISSUE THREAD

**Issue by ebizmis** [zhw2590582/flv-player#22]
只播放一个aac音频文件好像不能，设置hasVideo:false也不行

**Comment by zhw2590582** [comment]
不是很明白，假如是aac文件，直接用原生audio标签播放不好吗？

**Comment by ebizmis** [comment]
但是要直播实时生成aac，事后可以直接用audio播放

**Comment by zhw2590582** [comment]
这种情况不适合使用`flvplayer`，实时播放语音比较简单，其实不需要任何库都可以实现，详情可以了解下 [AudioContext](https://developer.mozilla.org/zh-CN/docs/Web/API/AudioContext).
