### ISSUE TITLE
结合vue的问题

### ISSUE THREAD

**Issue by Jkoala** [zhw2590582/flv-player#23]
Unable to find global variable 'FlvplayerDecoder' from './flvplayer-decoder-baseline.js'

**Comment by zhw2590582** [comment]
应该也是vue-cli的静态资源路径问题吧。
https://github.com/zhw2590582/FlvPlayer/issues/19#issuecomment-571516411

**Comment by gitxiaogui** [comment]
这个问题是你需要把这个文件下载下来，放到你的服务器上就好了，但是会有一个问题，视频画面一直在加载中，一直不出来画面，不知道你那边会不会有这个问题
