### ISSUE TITLE
hight profile 视频播放不了

### ISSUE THREAD

**Issue by ChungTak** [zhw2590582/flv-player#25]
测试视频
https://1011.hlsplay.aodianyun.com/demo/game.flv  

重现过程
1） 打开demo页面https://flvplayer.js.org/
2） 填写url,decoder改为flvplayer-decoder-multiple.js, hasAudio设置为false
3）  点击Run Code 然后播放，调试控制台无错误，画面出不来。live 设置为true也不行

FlvPlayer: [stream-end],1764177 byte
FlvPlayer: [flv-header],{ signature: FLV, version: 1, flags: 5, headersize: 9 }
FlvPlayer: [AudioSpecificConfig],{ audioObjectType: 2, samplingFrequencyIndex: 4, channelConfiguration: 2 }
FlvPlayer: [AAC-codecs],mp4a.40.2
FlvPlayer: [AVCDecoderConfigurationRecord],{ configurationVersion: 1, AVCProfileIndication: 100, profile_compatibility: 0, AVCLevelIndication: 30, lengthSizeMinusOne: 4, numOfSequenceParameterSets: 1, sequenceParameterSetLength: 30, numOfPictureParameterSets: 1, pictureParameterSetLength: 5 }
FlvPlayer: [AVC-codecs],avc1.6401e
FlvPlayer: [AVC-profile],High
FlvPlayer: [AVC-level],3.0

**Comment by zhw2590582** [comment]
解码器无法解码，可以换种profile试试

**Comment by Chensww** [comment]
Access to fetch at 'http://127.0.01:8000/live/liu.flv' from origin 'http://192.168.1.18:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
跨域怎么解决

**Comment by zhw2590582** [comment]
@Chensww 也只能服务器修改响应头了`Access-Control-Allow-Origin`

**Comment by Chensww** [comment]
好的，已经解决了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Harvey Zack"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 晚上6:39
收件人: "zhw2590582/FlvPlayer"<FlvPlayer@noreply.github.com&gt;; 
抄送: "执笔沉思"<985671526@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [zhw2590582/FlvPlayer] hight profile 视频播放不了 (#25)





 
@Chensww 也只能服务器修改响应头了Access-Control-Allow-Origin

**Comment by Chensww** [comment]
我按文档说明来的，直播流响应状态码200，怎么播放不了

**Comment by zhw2590582** [comment]
@Chensww 看看debug打印了什么

**Comment by Chensww** [comment]
![image](https://user-images.githubusercontent.com/20715376/79625727-81edac00-815d-11ea-86e1-d6f39df7235b.png)
只是一个警告提示

**Comment by zhw2590582** [comment]
@Chensww 有一个debug选项的，你没打开
