### ISSUE TITLE
直播flv无法解码，花屏

### ISSUE THREAD

**Issue by kernelj** [zhw2590582/flv-player#26]
Duration: N/A, start: 0.010000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 44100 Hz, 2.1, fltp, 1 kb/s
    Stream #0:1: Video: h264 (High), yuv420p(progressive), 1280x720, 18 fps, 18 tbr, 1k tbn, 36 tbc

**Comment by zhw2590582** [comment]
解码器无法解码，可以换种profile试试

**Comment by kernelj** [comment]
2种解码都试过了 baseline 不行，另外一个就是花屏

**Comment by zhw2590582** [comment]
可以尝试把flv的profile转为baseline吗？

**Comment by kernelj** [comment]
> 可以尝试把flv的profile转为baseline吗？

我是用srs有什么好的转码方案吗

**Comment by zhw2590582** [comment]
`ffmpeg`

**Comment by kernelj** [comment]
> `ffmpeg`

转为baseline 可以播放了，另外视频的宽度和高度不能适应视频的宽高吗，刚开始播放时比例显示不对，但是当触发了最大化在还原回来时候，视频比例就正确了

**Comment by kernelj** [comment]
解码的文件好像偏大，有办法变小一些吗

**Comment by kernelj** [comment]
用baseline解码渲染出来的画面比canvas要大很多，没办法全部显示在canvas内

**Comment by zhw2590582** [comment]
打开debug选项，看看有没有宽度和高度信息，再看看canvas的高度和宽度，能不能对上

**Comment by gitxiaogui** [comment]
我用你的线上演示版直接替换我的直播流地址，怎么播放不了，自己写的demo也是一直在加载中，不报错，就是不显示视频画面，流的地址是有效的，两个解析方式都试了，都是一直在加载中，显示不出来画面
