### ISSUE TITLE
直播流一直显示加载中，不显示画面

### ISSUE THREAD

**Issue by gitxiaogui** [zhw2590582/flv-player#27]
自己写的demo也是一直在加载中，不报错，就是不显示视频画面，用你的线上演示版直接替换我的直播流地址，也是播放不了的，流的地址是有效的，两个解析方式都试了，都是一直在加载中，显示不出来画面

**Comment by zhw2590582** [comment]
可以打开`debug`选项看看日志先

**Comment by gitxiaogui** [comment]
FlvPlayer: [play-retry] 
decoding: {video: true, audio: true}
playing: {video: false, audio: false}
streaming: true
日志一直是打印这个

**Comment by zhw2590582** [comment]
这么少的日志！应该很多信息才对的

**Comment by gitxiaogui** [comment]
没有啊，现在我边打印的都是这个日志信息

- 

- [ ] 
![image](https://user-images.githubusercontent.com/34672174/80173175-94fef100-8621-11ea-8544-10f176798156.png)

**Comment by zhw2590582** [comment]
有外网可以访问的flv地址吗？我看看

**Comment by gitxiaogui** [comment]
https://flv.6721.liveplay.now.qq.com/live/6721_49484dbf5537f37a0249980649dda08a.flv?txSecret=22d3539da8b577606a8cd50e14612831&txTime=5EA26E11
http://newlive.17kuxiu.com/live/30310_77777000194.flv
这两个地址我是直接放到你那个演示版demo里边的，都是不行，你看下

**Comment by gitxiaogui** [comment]
http://newlive.17kuxiu.com/live/30310_77777000194.flv

**Comment by zhw2590582** [comment]
我试了，看到了画面了啊

```js
var flv = new FlvPlayer({
    container: '.flvplayer-app',
    url: 'http://newlive.17kuxiu.com/live/30310_77777000194.flv',
    decoder: './uncompiled/flvplayer-decoder-multiple.js',
    debug: true,
    live: true,
    autoPlay: true,
    hasAudio: false,
    width: 960,
    height: 540,
});
```

**Comment by zhw2590582** [comment]
两个地址都是可以的

```js
var flv = new FlvPlayer({
    container: '.flvplayer-app',
    url: 'https://flv.6721.liveplay.now.qq.com/live/6721_49484dbf5537f37a0249980649dda08a.flv?txSecret=22d3539da8b577606a8cd50e14612831&txTime=5EA26E11',
    decoder: './uncompiled/flvplayer-decoder-multiple.js',
    debug: true,
    live: true,
    autoPlay: true,
    hasAudio: true,
    width: 960,
    height: 540,
});
```

**Comment by gitxiaogui** [comment]
你代码能发我下不，我这边还是不行

**Comment by gitxiaogui** [comment]
你在你的线上演示地址里边能播放吗？

**Comment by gitxiaogui** [comment]
我们的uncompiled/flvplayer-decoder-multiple.js这个文件是放到了服务器上边，在本地引入的，跟这个有关系吗

**Comment by zhw2590582** [comment]
decoder放哪里都没关系的，只要不跨域

[demo](https://flvplayer.js.org/?libs=.%2Funcompiled%2Fflvplayer-control.js&code=var%20flv%20%3D%20new%20FlvPlayer(%7B%0A%20%20%20%20container%3A%20%27.flvplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fflv.6721.liveplay.now.qq.com%2Flive%2F6721_49484dbf5537f37a0249980649dda08a.flv%3FtxSecret%3D22d3539da8b577606a8cd50e14612831%26txTime%3D5EA26E11%27%2C%0A%20%20%20%20decoder%3A%20%27.%2Funcompiled%2Fflvplayer-decoder-multiple.js%27%2C%0A%20%20%20%20debug%3A%20true%2C%0A%20%20%20%20live%3A%20true%2C%0A%20%20%20%20autoPlay%3A%20true%2C%0A%20%20%20%20hasAudio%3A%20true%2C%0A%20%20%20%20width%3A%20960%2C%0A%20%20%20%20height%3A%20540%2C%0A%7D)%3B)

**Comment by gitxiaogui** [comment]
我再研究下吧，好奇怪0.0

**Comment by ztz070306011** [comment]
我这边也不行，用demo的流是可以的，可能是什么原因呢
