### ISSUE TITLE
谷歌浏览器  ws-flv 视频流 播放只有画面没有声音

### ISSUE THREAD

**Issue by hadeswang2016** [zhw2590582/flv-player#28]
谷歌浏览器  ws-flv 视频流 播放只有画面没有声音

**Comment by zhw2590582** [comment]
打开debug选项，看看有什么信息

**Comment by hadeswang2016** [comment]
![image](https://user-images.githubusercontent.com/18191772/80438484-e0bddd00-8936-11ea-9a3d-95e61f705d8b.png)
一开始就报这个错误
然后现在改成http-flv 可以了  但是 console 会报这个错误 见截图

**Comment by hadeswang2016** [comment]
把ws换成http 可以播放 声音 但是 console 一开始加载 会报错  如下 
**Uncaught FlvPlayerError: PrevTagSize0 should be equal to 0, but got 12769**
    at Object.error (blob:http://demo.com/f6b665a8-ea5f-4ca7-92e3-e48b7c5ba4c9:1:3724)
    at onmessage (blob:http://demo.com/f6b665a8-ea5f-4ca7-92e3-e48b7c5ba4c9:1:10745)

**Comment by hadeswang2016** [comment]
![image](https://user-images.githubusercontent.com/18191772/80438484-e0bddd00-8936-11ea-9a3d-95e61f705d8b.png)
一开始就报这个错误
然后现在改成http-flv 可以了  但是 console 会报这个错误 见截图

**Comment by zhw2590582** [comment]
应该是一个直播流里出现多个flv，就像自动重连引起的，目前还没处理这种情况
