### ISSUE TITLE
希望作者大大好好调教移动端

### ISSUE THREAD

**Issue by DricHao** [zhw2590582/flv-player#3]
实际需求还是h5更大。 而且通过canvas绘制的视频，能够完美解决国内QQ 和 UC等流氓浏览器的劫持video标签的问题。 自己试了下，小米6原生浏览器没有音频。

**Comment by zhw2590582** [comment]
移动端坑还是很多的，而且我是觉得这种移动端播放flv的需求很少，而且软解码有很多格式限制，占用内存也很大

**Comment by DricHao** [comment]
> 移动端坑还是很多的，而且我是觉得这种移动端播放flv的需求很少，而且软解码有很多格式限制，占用内存也很大

我现在是用rtmp服务器做直播的一个项目。现在处理方式就是flv.js跑安卓。 hls跑IOS 。问题还是很多

**Comment by HUGY1** [comment]
> > 移动端坑还是很多的，而且我是觉得这种移动端播放flv的需求很少，而且软解码有很多格式限制，占用内存也很大
> 
> 我现在是用rtmp服务器做直播的一个项目。现在处理方式就是flv.js跑安卓。 hls跑IOS 。问题还是很多

俺也一样 除了hls延迟大点 没啥问题

**Comment by DricHao** [comment]
> > > 移动端坑还是很多的，而且我是觉得这种移动端播放flv的需求很少，而且软解码有很多格式限制，占用内存也很大
> > 
> > 
> > 我现在是用rtmp服务器做直播的一个项目。现在处理方式就是flv.js跑安卓。 hls跑IOS 。问题还是很多
> 
> 俺也一样 除了hls延迟大点 没啥问题

直播项目，视频播放区域是整铺满在页面最低的层级， 使用html5无法在UC浏览器实现， 他会劫持掉video标签然后覆盖到最高层级。 最好的解决方案就是作者这种canvas实现

**Comment by amhoho** [comment]
支持+1,目前我也是flv+hls两个,但是在手机版除了自己的APP,别的厂商几乎都劫持了video,造成没有一个能正常播放.不得已加了个websocket+jsmpeg,但是经常也出现卡顿各种问题.比较mpeg1-ts实在太古老了.这个项目如果能不断优化调试,相信会有许多了关注.
