### ISSUE TITLE
FlvPlayer: [stream-type],Try use ReadableStream

### ISSUE THREAD

**Issue by fralychen** [zhw2590582/flv-player#30]
chrome
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

online:
FlvPlayer: [stream-type],Try use ReadableStream

liveStrem:
`http://play.whca.org.cn/brand/48b2a766-f2f3-4c51-a23c-ec99737e5bd8.flv?auth_key=1597*****6-10734-0-********d42f6f1e157e54`

**Comment by zhw2590582** [comment]
???

**Comment by fralychen** [comment]
用chrome在您的线上demon测试的、
报错
![image](https://user-images.githubusercontent.com/30365766/81893330-09ed9700-95e0-11ea-8239-edd874cac476.png)

**Comment by zhw2590582** [comment]
你的url是http，我网站是https，这样是请求不到数据的

**Comment by fralychen** [comment]
好尴尬、谢啦
