### ISSUE TITLE
如何实现全屏播放啊，感觉点击视频的全屏并没有实现整个页面全屏 上面和底部仍然存在

### ISSUE THREAD

**Issue by 15869394691** [zhw2590582/flv-player#31]
Before mentioning Issue, please send the operating system, browser and version, and debug information together. If there is a flv address that can be accessed from the Internet, it will be more perfect to save time and troubleshoot the problem. Thank you.

在提Issue之前，请把操作系统，浏览器和版本，和debug信息也一起发出来，假如有一个外网可以访问的flv地址那就更完美了，以节省时间并排查问题，谢谢。

**Comment by zhw2590582** [comment]
手机浏览器限制了，除了原生视频以外元素，都无法真正全屏的

**Comment by 15869394691** [comment]
有没有曲线救国的办法呢 能实现在微信浏览器里全屏

**Comment by zhw2590582** [comment]
不知道微信有没有自带的功能可以隐藏菜单栏和顶部的，你可以搜索一下，有的话我也加进去

**Comment by 15869394691** [comment]
不知道 WeixinJSBridge.call('hideOptionMenu'); 和WeixinJSBridge.call('hideOptionMenu'); 链接: http://www.75271.com/1734.html 这两个方法有没有用

**Comment by zhw2590582** [comment]
那你可以先测试一下有没有用，这个api可能需要微信的SDK

**Comment by 15869394691** [comment]
试过了 隐藏底部的可以 但是顶部的导航栏不行，但奇怪的是 安卓的可以全屏（不能横屏全屏），ios的却是连全屏都不可以
