### ISSUE TITLE
可以实现播放实时视频流吗

### ISSUE THREAD

**Issue by Owenli614625** [zhw2590582/flv-player#34]
我测试，播放实时视频流的时候，没有画面。

**Comment by zhw2590582** [comment]
你可以把debug信息发出来吗?

**Comment by Owenli614625** [comment]
FLV封装的是纯的H264视频流，没有音频数据。FLV 封装视频应该没有问题，PC端用flv.js可以正常播放。
![image](https://user-images.githubusercontent.com/51768146/84246124-b1ef7500-ab38-11ea-81c8-cc353441cfd9.png)

**Comment by zhw2590582** [comment]
你要换个解码器

**Comment by Owenli614625** [comment]
说具体点

**Comment by Owenli614625** [comment]
换了个解码器 ./uncompiled/flvplayer-decoder-multiple.js 在移动端可以播放flv封装的纯的H264数据
