### ISSUE TITLE
切换浏览器标签页画面会卡住

### ISSUE THREAD

**Issue by Owenli614625** [zhw2590582/flv-player#35]
切换浏览器标签页画面会卡住，可以在实现直播的效果吗，切换标签页并不卡住画面，

**Comment by zhw2590582** [comment]
不是卡住，假如切出去了会暂停，再切回来的话，会播放最新的画面。

**Comment by Owenli614625** [comment]
切换标签页，貌似会把数据缓存起来，等再切回标签页的时候画面会接着让一次切出去的的时间点播放，这样就出现了延时的现象。

**Comment by zhw2590582** [comment]
直播是不会保存数据的，播完就丢弃，切回去的逻辑也是播放最新的，可能是其他原因引起延迟的

**Comment by Owenli614625** [comment]
那可能是我调用的方式不对。我仔细看看代码&nbsp;




李阳
陕西中达公路技术服务有限公司


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Harvey Zack"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 下午4:02
收件人: "zhw2590582/FlvPlayer"<FlvPlayer@noreply.github.com&gt;; 
抄送: "LY"<1813614625@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhw2590582/FlvPlayer] 切换浏览器标签页画面会卡住 (#35)





 
直播是不会保存数据的，播完就丢弃，切回去的逻辑也是播放最新的，可能是其他原因引起延迟的
