### ISSUE TITLE
移动端不能拖动进度

### ISSUE THREAD

**Issue by 965390267** [zhw2590582/flv-player#36]
Before mentioning Issue, please send the operating system, browser and version, and debug information together. If there is a flv address that can be accessed from the Internet, it will be more perfect to save time and troubleshoot the problem. Thank you.

在提Issue之前，请把操作系统，浏览器和版本，和debug信息也一起发出来，假如有一个外网可以访问的flv地址那就更完美了，以节省时间并排查问题，谢谢。

**Comment by 965390267** [comment]
微信端，全屏无效

**Comment by zhw2590582** [comment]
本来canvas就是无法在手机端全屏的，所以只能模拟全屏。
移动端我故意设置了不缓存，以优化内存释放的。
