### ISSUE TITLE
浏览器最小化之后视频暂停播放

### ISSUE THREAD

**Issue by evilArsh** [zhw2590582/flv-player#4]
你好我遇到个问题，就是浏览器最小化之后视频暂停播放，但是打开浏览器之后视频又继续播放了，我是播放的实时视频。如果最小化一段时间之后，再最大化播放，他是接着之前最小化的时候的时间点放的，这样的话视频就不是实时的了。请问有什么处理方法嘛

**Comment by zhw2590582** [comment]
因为播放是依赖于`window.requestAnimationFrame`，假如当前标签页面不是激活状态，它为了优化性能会运行得很慢甚至不运行，所以我控制了假如当前标签不可见，干脆暂停视频，这个对于直播确实不太合理。
至于flv直播这块，坑比较多，最近还在优化中。

**Comment by evilArsh** [comment]
在浏览器层面可以屏蔽掉这个策略吗？比如给chrome添加命令行使得在后台也可以播放。因为我用的electron做客户端，本质是用chrome渲染。而且最近项目要上线了，急得很，虽然有一些解决方法，比如当标签不可见再可见之后，调整video标签的currenttime为当前buffed的时间。我可以加你联系方式吗，或者发邮件都可以1183520543@qq.com。希望你能看到这个消息，😂确实是无法了

**Comment by zhw2590582** [comment]
@evilArsh 既然你用在electron，那flv.js不是应该更合适么，我这是用canvas渲染的，没有video这个标签。有问题的话，可以加下面的QQ群交流。

**Comment by evilArsh** [comment]
谢谢啦
