### ISSUE TITLE
iPad 创建FlvPlayer失败

### ISSUE THREAD

**Issue by JoinJun** [zhw2590582/flv-player#40]
设备： iPad Pro
版本： 13.5.1
代码：
      let div = this.divContainer.get(url);
      if (!div) {
        div = document.createElement('div');
        this.divContainer.set(url, div);
      }

      var flv = new FlvPlayer({
        // Accept http url, websocket url, and file type
        url: '/assets/images/weathering-with-you.flv',

        // Accept dom element, dom selector
        container: div,

        // Video poster url
        poster: '',

        // Whether to print debug information
        debug: true,

        // Whether live mode
        live: false,

        // Whether the video loops, in non-live mode
        loop: true,

        // Whether to use hotkeys, if the control exists
        hotkey: true,

        // Whether to turn off the volume
        muted: true,

        // On the mobile side, try to activate the audio after the user touches the screen.
        touchResume: false,

        // Video chunk size, the default is 1M
        videoChunk: 1024 * 1024,

        // Audio chunk size, the default is 16kb
        audioChunk: 16 * 1024,

        // Whether to play automatically
        autoPlay: true,

        // Whether it contains an audio stream
        hasAudio: false,

        // Whether to cache the video frame to play
        cache: true,

        // Maximum time difference between audio and video, unit is ms
        // used to automatically adjust audio and video synchronization
        maxTimeDiff: 200,

        // Whether to display the control, if the control exists
        control: false,

        // Indicates whether to do http fetching with cookies
        withCredentials: true,

        // Indicates total file size of media file, in bytes
        filesize: Infinity,

        // Indicates whether to enable CORS for http fetching
        cors: true,

        // Volume from 0 to 1, the default is 0.7
        volume: 0.7,

        // Initialize the frame rate, which will be covered by the actual frame rate of the file
        frameRate: 30,

        // Initialize the width, which will be covered by the actual width of the file
        width: 1920,

        // Initialize the height, which will be covered by the actual height of the file
        height: 1080,

        // Initialize http headers
        headers: {},

        // The path of the video decoder, currently optional flvplayer-decoder-baseline.js and flvplayer-decoder-multiple.js
        decoder: 'assets/flvplayer-decoder-baseline.js',
      });

      flv.on('play', () => {
        console.log('flv play');
      })

    } else {
      console.warn('Your browser does not support Flvplayer.js');
    }
打印： 
2020-08-25 17:26:25.616521+0800 可视化终端[62420:2512690] WARN: Your browser does not support Flvplayer.js
2020-08-25 17:26:45.305129+0800 可视化终端[62420:2512690] WARN: Your browser does not support Flvplayer.js
2020-08-25 17:26:45.314879+0800 可视化终端[62420:2512690] WARN: Your browser does not support Flvplayer.js
2020-08-25 17:26:45.316417+0800 可视化终端[62420:2512690] WARN: Your browser does not support Flvplayer.js

上面的代码使用ionic打包在iPad上运行会提示不支持。这个是什么原因？

**Comment by zhw2590582** [comment]
说明ipad上面不支持视频软解码，目前无解。

**Comment by JoinJun** [comment]
谢谢
