### ISSUE TITLE
启动报错- v1.1.8

### ISSUE THREAD

**Issue by sjzgit** [zhw2590582/flv-player#41]
![image](https://user-images.githubusercontent.com/26371424/92985708-b2a4f800-f4e7-11ea-84ad-07e3df9bf862.png)
最新版本引入报语法错误~

**Comment by zhw2590582** [comment]
这其实不是flvplayer的报错，可以参考一下这个：https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b
