### ISSUE TITLE
multiple decode.worker的源码

### ISSUE THREAD

**Issue by turengege** [zhw2590582/flv-player#43]
可以提供下multiple decoder.worker的源码么？

在使用multiple decoder的过程中，发现部分流会出问题

**Comment by zhw2590582** [comment]
源码是C语音：https://github.com/oneam/h264bsd

**Comment by turengege** [comment]
> 源码是C语音：https://github.com/oneam/h264bsd

感谢回复， 但是h264bsd只支持 baseline和constrained baseline吧, 希望得到multiple的源码

**Comment by zhw2590582** [comment]
哈哈，我已经忘了multiple的源码从哪里编译来的了，不好意思哈
