### ISSUE TITLE
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page

### ISSUE THREAD

**Issue by massive688** [zhw2590582/flv-player#44]
首先感谢作者的开源，这是个非常棒的项目
问题一：
Google Chrome
版本 87.0.4280.88（正式版本） （64 位）
出现声音无法自动播放的问题

警告：The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page

这个声音自动播放还会持续改进吗

问题二：
页面切换到其他页面时，视频会自动暂停，这是可以配置的吗？还是就是这么设计的。
有很多场景是页面切换了，当前活跃的页面不是视频页面，还是希望让他继续播放。这可以改进吗

**Comment by zhw2590582** [comment]
问题一是浏览器自身的限制，视频或者音频在用户发生交互（如点击）前，都不允许播放声音的。
问题二是因为性能考虑使用了`requestAnimationFrame`的缘故，其实只要用`setTimeout`就可以解决，我后续想想怎么把这个写成可选的选项

**Comment by massive688** [comment]
感谢作者的解惑，关于问题二能后续改进那真是太好了：）。关于问题一，希望可以交流一下。一般视频网站的广告视频打开页面会自动播放音视频。可能会使用到flash技术。是不是像大型的主流视频网站（如优酷，爱奇艺，腾讯）都是这么做的使用了flash

**Comment by zhw2590582** [comment]
不是的，只是因为大型视频网站（如B站）在google chrome的内置白名单里，允许这样做
