### ISSUE TITLE
一个页面同时开启12个FlvPlayer会卡顿，其中几个FlvPlayer无画面，有画面的画面不动

### ISSUE THREAD

**Issue by nocpp** [zhw2590582/flv-player#48]
操作系统： MacOS Big Sur 11.2.3
浏览器：Chrome 92.0.4515.131

大佬你好，我在一个页面同时开启了12个FlvPlayer播放监控视频，会很卡，有些视频加载不出来，加载出来的画面不动。过一会儿浏览器会提示，喔唷，崩溃啦。

播放1个视频没问题，可以正常播放。

**Comment by zhw2590582** [comment]
为什么要开启12个FlvPlayer，软解码本来就是很吃内存的

**Comment by nocpp** [comment]
> 为什么要开启12个FlvPlayer，软解码本来就是很吃内存的

谢谢大佬回复，业务是要同时看12个监控视频，这只能提升电脑配置来解决了吗

**Comment by zhw2590582** [comment]
最好办法是在服务器上合并这12个视频成一个视频，但这也增加一定延迟

**Comment by nocpp** [comment]
> 最好办法是在服务器上合并这12个视频成一个视频，但这也增加一定延迟

好的，谢谢大佬
