### ISSUE TITLE
直接播放有个报错

### ISSUE THREAD

**Issue by AmpletecGo** [zhw2590582/flv-player#5]
Uncaught FlvPlayerError: AMF: [amf2] type expect 8, but got 3
    at Object.error (blob:http://192.168.0.158:8080/9d44f831-74b1-4355-8d94-a8f33954dd7d:1:3393)
    at demuxerScripTag (blob:http://192.168.0.158:8080/9d44f831-74b1-4355-8d94-a8f33954dd7d:1:5612)
    at onmessage (blob:http://192.168.0.158:8080/9d44f831-74b1-4355-8d94-a8f33954dd7d:1:10909)

**Comment by AmpletecGo** [comment]
能正常播放就是有个报错

**Comment by zhw2590582** [comment]
一个容错问题，我修复下

**Comment by AmpletecGo** [comment]
![image](https://user-images.githubusercontent.com/25581029/62116667-2472b000-b2ed-11e9-8358-223bf1922796.png)
现场是报这个

**Comment by zhw2590582** [comment]
应该flv流不是规范格式，你可以在`/src/demuxer/demuxer.worker`，找到删掉这个错误警告，再试试。

**Comment by AmpletecGo** [comment]
好的，谢谢。那如何知道 flv 流是否规范格式呢？

**Comment by zhw2590582** [comment]
这个有点难判断，所以我尽量按照文档来对flv解封装，但就算有的地方不规范也可以播放。

**Comment by sunjun** [comment]
你好，我也遇到这个问题，但是不能正常播放，视频流用vlc是可以正常播放的，不知道用flvplayer怎么修改能成功播放

> ![image](https://user-images.githubusercontent.com/25581029/62116667-2472b000-b2ed-11e9-8358-223bf1922796.png)
> 现场是报这个

**Comment by sunjun** [comment]
> 你好，我也遇到这个问题，但是不能正常播放，视频流用vlc是可以正常播放的，不知道用flvplayer怎么修改能成功播放
> 
> > ![image](https://user-images.githubusercontent.com/25581029/62116667-2472b000-b2ed-11e9-8358-223bf1922796.png)
> > 现场是报这个

经过修改可以了原来是设置的fps不对导致的

**Comment by AmpletecGo** [comment]
> > 你好，我也遇到这个问题，但是不能正常播放，视频流用vlc是可以正常播放的，不知道用flvplayer怎么修改能成功播放
> > > ![image](https://user-images.githubusercontent.com/25581029/62116667-2472b000-b2ed-11e9-8358-223bf1922796.png)
> > > 现场是报这个
> 
> 经过修改可以了原来是设置的fps不对导致的

请问你是如何设置 fps 的？

**Comment by sunjun** [comment]
> > > 你好，我也遇到这个问题，但是不能正常播放，视频流用vlc是可以正常播放的，不知道用flvplayer怎么修改能成功播放
> > > > ![image](https://user-images.githubusercontent.com/25581029/62116667-2472b000-b2ed-11e9-8358-223bf1922796.png)
> > > > 现场是报这个
> > 
> > 
> > 经过修改可以了原来是设置的fps不对导致的
> 
> 请问你是如何设置 fps 的？

var flv = new FlvPlayer({
    container: '.flvplayer-app', // A div dom element
    url: 'path/to/video.flv', // Url of flv video file or url of websocket
    decoder: './flvplayer-decoder-baseline.js', // Path to video decoder, flvplayer-decoder-baseline.js or flvplayer-decoder-multiple.js
    poster: 'path/to/poster.png', // Url of video poster, the first frame of the video is taken as the poster by default
    autoPlay: false, // Whether auto play
    debug: false, // Show debug information on developer tools
    live: false, // Whether live video
    loop: false, // Whether to automatically loop play
    hotkey: true, // Whether to use hotkeys
    hasAudio: true, // Whether to include audio
    volume: 7, // Default volume, ranging from 0 to 10
    frameRate: 30, // Video frame rate, which will be extracted from the flv file by default
    width: 400, // Video default width, which will be extracted from the flv file by default
    height: 300, // Video default height, which will be extracted from the flv file by default
});

就是这个    frameRate: 30, // Video frame rate, which will be extracted from the flv file by default
参数

**Comment by zhw2590582** [comment]
已经把这个错误改成警告形.
