### ISSUE TITLE
全屏是不是有问题

### ISSUE THREAD

**Issue by DraCod** [zhw2590582/flv-player#52]
移动端全屏放大不准确，位置偏移了好多

**Comment by zhw2590582** [comment]
什么手机呢，能否提供一下截图

**Comment by DraCod** [comment]
xs max，从上往下，放大之后分辨率就变了
![wecom-temp-a9d6057c6cdc01f41865dab3d740c61d](https://user-images.githubusercontent.com/45255009/145942822-fdfa279a-54d4-4ae9-a4e5-65b24dd06fa0.jpg)
![wecom-temp-7f23e8ac03539c55a928634e1a012b3a](https://user-images.githubusercontent.com/45255009/145942834-aa1879bf-5949-4011-be44-cf4171467bab.jpg)
![wecom-temp-651079a9df6b600ad90478bccbb9c6ab](https://user-images.githubusercontent.com/45255009/145942853-3b228859-48b3-4db8-b5a0-2d2556f33e13.jpg)

**Comment by zhw2590582** [comment]
有没有外网可以访问的地址呢，你可以发到我的邮箱

**Comment by DraCod** [comment]
没有外网地址……

**Comment by zhw2590582** [comment]
那你可以手动调试一下，不会太复杂，旋转缩放的逻辑在这里

https://github.com/zhw2590582/FlvPlayer/blob/9aa87581781e7f281d3110252e994aff35936554/src/control/property.js#L78
