### ISSUE TITLE
[BUG] IOS无法播放

### ISSUE THREAD

**Issue by DricHao** [zhw2590582/flv-player#6]
系统版本： IOS12.2
浏览器：QQ浏览器9.2.0.4121
报错信息： FlvPlayerError: streamID should be wquals to 0, but get 5243211(数字一直变化)
浏览器： Chrome浏览器67.0.3396.87
报错信息：TypeError: undefined is not an object (near '...}).catch(function () {...'}) 可以播放但是会在短时间内造成页面崩溃

相关操作： 我使用手机访问电脑版DEMO，因为手机版demo并没有声音（不知道是否支持开启声音）。安卓访问电脑版demo无报错正常运行，IOS遇到上述问题

**Comment by zhw2590582** [comment]
QQ 手机浏览器有兼容问题，但目前还没开始排查。页面奔溃问题估计是因为点播缓存的数据太大，造成占用内存太多导致的，这个还没找到好的解决办法。Demo没声音是因为我还没调试完手机的音频接口，我后面会优化这个的。

**Comment by DricHao** [comment]
> QQ 手机浏览器有兼容问题，但目前还没开始排查。页面奔溃问题估计是因为点播缓存的数据太大，造成占用内存太多导致的，这个还没找到好的解决办法。Demo没声音是因为我还没调试完手机的音频接口，我后面会优化这个的。

awesome!
