### ISSUE TITLE
简化版的分支

### ISSUE THREAD

**Issue by AmpletecGo** [zhw2590582/flv-player#7]
能否创建一个简化版的分支，即是去掉所有 class html controls hotkey，只保留播放

**Comment by zhw2590582** [comment]
这些全部都可以设置为`false`，假如你是想完全把这些代码都删掉的话，那需要定制一下

**Comment by zhw2590582** [comment]
@AmpletecGo 现在已经把相关UI分离出来了，UI可以单独可选安装。
