### ISSUE TITLE
视频解码方案

### ISSUE THREAD

**Issue by AmpletecGo** [zhw2590582/flv-player#8]
看看能否参考下这个项目
https://github.com/matijagaspar/ws-avc-player

**Comment by zhw2590582** [comment]
之前看过这个，我后面看能不能也把它也加进可选的解码器里面

**Comment by AmpletecGo** [comment]
主要是现在的解码效率好像有点低，很容易就把手机卡死了

**Comment by q2922102693** [comment]
内存一直在飙升是导致卡死的原因

**Comment by zhw2590582** [comment]
因为做点播的时候需要缓存已播放的大容量信息

**Comment by q2922102693** [comment]
直播的时候也一直在飙升

**Comment by zhw2590582** [comment]
这就难搞了

**Comment by AmpletecGo** [comment]
我看到有人使用 flv.js + Broadway.js + websocket 来播放 flv stream

**Comment by ErosZy** [comment]
可以移植一下我的[WXInlinePlayer](https://github.com/qiaozi-tech/WXInlinePlayer)的算法，来解决这个播放器的内存占用问题。

目前使用你的示例视频，稳定在140-170M区间，之后会进一步逐步优化内存占用，使得1080P的长影片稳定在200-300M内存消耗。

UPDATE:
现已支持1080P的播放，并且1080P内存占用很稳定。

**Comment by AmpletecGo** [comment]
> 这就难搞了

@zhw2590582 Harvey Zack 
关于内存飙升，我觉得是否把直播与点播拆分下代码？因为在直播时 decoder/video/baseline/index.js 下的 videoframes 一直在保存旧的 frame 信息。

**Comment by zhw2590582** [comment]
直播已经很大程度的降低了内存占用，点播尚未作出更改。

**Comment by sunjun** [comment]
> 直播的时候也一直在飙升

@q2922102693 
我也遇到这个问题了 可以看一下这个提交，我这面测试直播的时候 可以解决内存泄漏问题
https://github.com/zhw2590582/FlvPlayer/pull/37
