### ISSUE TITLE
在浏览器上运行后报错了 no native wasm support detected

### ISSUE THREAD

**Issue by amhoho** [zhw2590582/flv-player#9]
具体:
no native wasm support detected
blob:ht...e383b7f (第 1 行)
TypeError: Module.asm.x is undefined
	

blob:ht...e383b7f (第 1 行)
Error: PrevTagSize0 should be equal to 0, but got -196608

**Comment by zhw2590582** [comment]
说明你的浏览器不支持`WebAssembly `，换个`chrome`试试

**Comment by amhoho** [comment]
chrome(版本 76.0.3809.132（正式版本） （64 位）)也不支持
移动端也全灭 都是这个提示

**Comment by zhw2590582** [comment]
直播还是点播？有没有url可以给我看看

**Comment by amhoho** [comment]
@zhw2590582 就你那个mobile.html的,另外直播也测试了,没有声音.
建议使用`worker`提升性能,另外`QQ/UC`的`fetch`均被阉割了,所以你这个也就无法播放了.

**Comment by zhw2590582** [comment]
已经用了两个`worker`了，直播没声音是因为我最近还在弄音视频同步，另外`fetch`是个很共用的接口，不会被阉割的，阉割应该是流处理的功能。

**Comment by amhoho** [comment]
@zhw2590582 音视频同步不会是说播放时还需要一个音频流和画面同步吧?那样直播就无意义了.再一个 `qq/uc`已经内部证实阉割了`fetch`.

**Comment by zhw2590582** [comment]
直播当然要音视频同步.
